### PR TITLE
fix(space-nuxt-base): catch FetchError correctly

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What?

`err instance of FetchError` works on development mode, but not on the production. So we're changing the way to check the error.

### Note

I was working on another ticket where we wanted to prevent user from  being redirected to /error.vue when a specific server error happens. I couldn't solve it yet. However, during the debugging, I've realized FetchError didn't work on the production, so I opened this PR independently.

### CODE REVIEW

**Review by Dawntraoz — DISMISSED** [review]

**Comment by BibiSebi** [comment]
While testing today the ìnstanceOf seemed to be working, I need to retry tomorrow.

**Comment by eunjae-lee** [comment]
> While testing today the ìnstanceOf seemed to be working, I need to retry tomorrow.

@BibiSebi  did you test it with `pnpm run build && pnpm run preview`?

**Comment by BibiSebi** [comment]
@eunjae-lee I just retested it on "production" with console log and it worked. 
image

**Comment by eunjae-lee** [comment]
Screenshot 2024-06-06 at 17 59 28

Screenshot 2024-06-06 at 17 59 35

Screenshot 2024-06-06 at 18 08 06

I've added a button that throws an error, and `err instanceof FetchError` was `false` in this test 🤔

I don't know how you tested it. Anyway this is not super urgent, so I'll keep this open until you come back and give it a test together!

**Pull request closed without merging**
